contributor = "03a74233-e792-41de-a581-ae1b9e8fe0a7"
language = "Chinese"
issue_auto_label = true
issue_auto_tidy = true
issue_close_with_report = true

# pr_auto_label = true
# pr_auto_review = true
# pr_auto_merge = true
